djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    #utiliza a variável importada
    path('admin/', admin.site.urls),

    #login
    path('accounts/', include('allauth.urls')),

    #local
    path("", include("pages.urls", namespace="pages"))

]

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView, name="home"),
    path("noticias/", views.Noticias.as_view(), name="noticias"),
    path("inserir-noticia/", views.inserir, name="inserirNoticia"),
    path("filtrar/", views.filtrarNoticia, name="filtrar"),
    path("filtrar-noticia/", views.filtrar, name="filtrarNoticia"),
]

pages/models.py
from django.db import models

# Create your models here.
class Noticia(models.Model):
    titulo = models.CharField(max_length=200)
    tag = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    image=models.CharField(max_length=10000)
    class Meta:
        db_table='pages_noticia'

pages/forms.py
from django.forms import ModelForm
from pages.models import Noticia

class NoticiaForm(ModelForm):
    class Meta:
        model = Noticia
        fields = '__all__'

djangoProject/views/login.py
##login do user com username e password
#não necessita de ser encriptado

djangoProject/views/time.py
# import Http Response from django
from django.http import HttpResponse
# get datetime
import datetime


# create a function
def geeks_view(request):
    # fetch date and time
    now = datetime.datetime.now()
    # convert to string
    html = "Time is {}".format(now)
    # return response
    return HttpResponse(html)

djangoProject/views/views.py
from pymongo import MongoClient
from django.http import HttpResponse

def inserirDados(teste):
    my_client = MongoClient("localhost", 27017)

    dbname = my_client['noticias'] #base de dados
    collection_name = dbname["collection"]

    #duas collections
    medicine_1 = {
        "medicine_id": "RR000123456",
        "common_name" : "Paracetamol",
        "scientific_name" : "",
        "available" : "Y",
        "category": "fever"
    }
    medicine_2 = {
        "medicine_id": "RR000342522",
        "common_name" : "Metformin",
        "scientific_name" : "",
        "available" : "Y",
        "category" : "type 2 diabetes"
    }

    # Insert the documents
    collection_name.insert_many([medicine_1,medicine_2])
    # Check the count
    #count = collection_name.count_documents()
    #print(count)

    # Read the documents
    #med_details = collection_name.find()

    # Print on the view
    #for r in med_details:
    return HttpResponse("oi")

pages/views.py
from django.shortcuts import render

# Create your views here.
from django.template.context_processors import request
from django.views.generic import TemplateView

#inserir noticia
from .forms import NoticiaForm
from pages.models import Noticia


def HomePageView(request):
    noticias = Noticia.objects.all()
    return render(request, "noticias.html", { 'noticias': noticias })


class Noticias(TemplateView):
    template_name = "noticias.html"

#insere a noticia na base de dados
def inserir(request):
    form = NoticiaForm()

    if(request.method == 'POST'):
        form = NoticiaForm(request.POST)

        if(form.is_valid()):
            form.save()


    context = {'form': form}
    return render(request, 'inserirNoticia.html', context)


def filtrarNoticia(request):
    if request.POST:
        tag = request.POST['selected_tag']
        noticias = Noticia.objects.all()
        list = []

        for noticia in noticias:
            if noticia.tag == tag:
                list.append(noticia)

        context = {'list': list, 'noticias': noticias}
        return render(request, 'filtrarNoticia.html', context)


def filtrar(request):
    noticias = Noticia.objects.all()
    return render(request, "filtrarNoticia.html", {'noticias': noticias})

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Notícias</a>
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url 'pages:inserirNoticia' %}">Inserir Notícia</a>
                    <a class="navbar-brand" href="{% url 'pages:filtrarNoticia' %}">Filtrar por Tag</a>
                {% endif %}
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/filtrarNoticia.html
{% extends 'base.html' %}

{% block title %}Notícias{% endblock %}

{% block content %}

   <h3>Filtrar notícias por tag</h3>

    <form method='post' action='/filtrar/'>
    {% csrf_token %}
        <select class="form-control" id="make" name='selected_tag' placeholder="Selecione uma tag">
            {% for noticia in noticias %}
                <option value='{{noticia.tag}}'>{{ noticia.tag }}</option>
            {% endfor %}
        </select>

    <button class="btn btn-success" type="submit">Filtrar</button>
    </form>

    {% for noticia in list %}

        <div class="card" style="width: 100%; margin: 10px">
            <img src={{ noticia.image }} class="card-img-top">
            <div class="card-body">
              <div style="display: flex; flex-direction: row">
                <h5 class="card-title">{{ noticia.titulo }}</h5>
              </div>
              <p class="card-text">{{ noticia.description }}</p>
              <a class="btn btn-primary">Tag: {{ noticia.tag}}</a>
            </div>
          </div>
    {% endfor %}

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Notícias{% endblock %}

{% block content %}
    Notícias

{% endblock %}

templates/inserirNoticia.html
{% extends 'base.html' %}

{% block title %}Notícias{% endblock %}

{% block content %}

    <h3>Inserir uma nova notícia</h3>
    <form action="/inserir-noticia/" method="POST">
    {% csrf_token %}
    {{form}}
        <input type="submit">
    </form>

{% endblock %}

templates/noticias.html
{% extends 'base.html' %}

{% block title %}Notícias{% endblock %}

{% block content %}

<h1>Lista de notícias</h1>
    {% for noticia in noticias %}

        <div class="card" style="width: 100%; margin: 10px">
            <img src={{ noticia.image }} class="card-img-top">
            <div class="card-body">
              <div style="display: flex; flex-direction: row">
                <h5 class="card-title">{{ noticia.titulo }}</h5>
              </div>
              <p class="card-text">{{ noticia.description }}</p>
              <a class="btn btn-primary">Tag: {{ noticia.tag}}</a>
            </div>
          </div>
    {% endfor %}
{% endblock %}